steps:
# Eliminar la carpeta /workspace si existe
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'rm -rf /workspace || true'

# Clonar el repositorio en /workspace/backend
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', "https://github.com/DevITandCo/EDUconline-backend", '/workspace/backend']

# Construir la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/astral-option-412114/apieduconline', '-f', '/workspace/backend/Dockerfile', '/workspace/backend']

# Empujar la imagen de Docker a gcr.io
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/astral-option-412114/apieduconline']
  
# Desplegar la aplicación en Google Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'backend'
  - '--image'
  - 'gcr.io/astral-option-412114/apieduconline'
  - '--region'
  - 'europe-west9'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--concurrency'
  - '80'
  - '--timeout'
  - '180s'
  - '--memory'
  - '256Mi'
  - '--set-env-vars'
  - 'MONGODB_URI=mongodb+srv://admin:HPvzCfgcWT1K0XuA@cluster.ukkr5pz.mongodb.net/?retryWrites=true&w=majority'

# Configuración de opciones global (incluyendo el cubo de registros y logging)
options:
  logging: CLOUD_LOGGING_ONLY
  build:
    logsBucket: 'gs://educonline_bucket'
    
images:
- 'gcr.io/astral-option-412114/apieduconline'
