name: Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud and Docker
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin gcr.io/${{ secrets.GCP_PROJECT_ID }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: "gcr.io/${{ secrets.GCP_PROJECT_ID }}/educonline-backend:${{ github.sha }}"
        secrets: |
            "mongodb_uri=${{ secrets.MONGODB_URI }}"
            "mail_user=${{ secrets.MAIL_USER }}"
            "mail_pass=${{ secrets.MAIL_PASS }}"
            "mail_proxy=${{ secrets.MAIL_PROXY }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set MongoDB URI and Email Config as environment variables
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
        echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> $GITHUB_ENV
        echo "MAIL_PASS=${{ secrets.MAIL_PASS }}" >> $GITHUB_ENV
        echo "MAIL_PROXY=${{ secrets.MAIL_PROXY }}" >> $GITHUB_ENV

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy educonline-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/educonline-backend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
